name: Daily Keepalive

on:
  schedule:
    - cron: '5 0 * * *' # daily at 00:05 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make daily commit
        run: |
          set -euo pipefail
          echo "Run at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" | tee -a .keepalive.log
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "$(date -u +"%F %T")Z ${GITHUB_RUN_NUMBER}" >> .keepalive
          git add .keepalive .keepalive.log || true
          git commit -m "chore: daily keepalive $(date -u +"%F") [skip ci]" || echo "No changes to commit"
          # Push to default branch (main) or current ref
          git push origin "${GITHUB_REF_NAME:-main}" || git push

      - name: Prepare run log
        run: |
          set -euo pipefail
          RUN_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          {
            echo "Workflow: ${GITHUB_WORKFLOW}"
            echo "Repository: ${GITHUB_REPOSITORY}"
            echo "Run URL: ${RUN_URL}"
            echo "Actor: ${GITHUB_ACTOR}"
            echo "Ref: ${GITHUB_REF}"
            echo "Time (UTC): $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            echo
            echo "Last commit:"
            git --no-pager log -1 --pretty=fuller --stat
          } > run.log

      - name: Send email with run log
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Daily keepalive #${{ github.run_number }} on ${{ github.repository }}"
          to: "g1547246193@gmail.com"
          from: "GitHub Actions <no-reply@github.com>"
          secure: true
          content_type: text/plain
          body: file://run.log
        continue-on-error: true

